### ISSUE TITLE
Surging.Hero常见问题

### ISSUE THREAD

**Issue by liuhll** [surging-cloud/Surging.Hero#12]
# 使用vs打开项目后,为什么无法加载项目?
因为透过`global.json`强制指定了 .net core sdk的版本为:2.2.300,如果你打开项目后无法加载项目,你可以通过下载[.net core sdk 2.2.300版本](#),如果你安装了其他.net core2.2,x版本的话,也可以通过删除或是修改`global.json`后重新打开解决方案即可。

# 为什么打开`Surging.Hero.sln`后无法找到surging组件?无法编译通过?
请先进入到`./framework/nupkg`目录中,通过powershell工具执行脚本，对surging组件进行打包。
```shell
cd ./framework/nupkg
./pack.ps1
```

# 为什么无法通过vs进行调试项目
需要将 `docker-compose`设置为启动项目,如果之前没有使用docker进行开发调试过.net core 相关项目的话,vs会通过网络下载相关vsdbg组件包,这个过程会比较慢。你可以通过我们给到的连接下载[vsdbg组件](#),然后解压到家目录下的`vsdbg`文件夹下。需要重新打开vs再进行调试操作

# 什么是家目录?
家目录是指当前用户登录的工作目录。一般的,linux系统下,用户登录后首先进入的就是该账户的家目录，root账户的家目录是:`/root`，其他账号的家目录在`/home`目录下,例如:账号`zhangsan`的家目录是`/home/zhangsan`。而windows的家目录是在c盘下的users目录下,例如：张三的家目录是在:`c:/users/zhangsan`。

# 项目启动后抛出异常?
请先启动基础设施服务。进入到`./hero/docker-compose/infrastr`,执行如下命令:
```
docker-compose up -d
```
> **notes**
> - 该项目开发调试重度依赖docker和docker-compose,请先安装docker for windows和docker-compose

**Comment by keepRunM** [comment]
![image](https://user-images.githubusercontent.com/29815398/63480888-40b9d500-c4c6-11e9-8c2d-594010e7a965.png)
大哥，这样是启动成功了吗？
